# NOTE: update this with your service name
service: authorization-service

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  profile: iam_admin_user
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  environment:
    ilya_moskovtsev: ${env:ilya_moskovtsev}

resources:
  Outputs:
    authArn:
      Value: ${self:custom.AUTH_ARN}

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer

custom:
  bundle:
    linting: false
  AUTH_ARN:
    Fn::GetAtt:
      - BasicAuthorizerLambdaFunction
      - Arn